my_string = input('Укажите имя и Фамилию:')
print(my_string.__len__())
print(my_string.upper())
print(my_string.upper().lower())
print(my_string.replace(' ', ''))
print(my_string[0])
print(my_string[-1])